ion_orresu_dict = {
    'H_in': ['H_in', 'mM'],
    'K_in': ['K_in', 'mM'],
    'Cl_in': ['Cl_in', 'mM'],
    'Na_in': ['Na_in', 'mM'],
    'H_out': ['H_out', 'mM'],
    'K_out': ['K_out', 'mM'],
    'Cl_out': ['Cl_out', 'mM'],
    'Na_out': ['Na_out', 'mM'],
    'ATP': ['ATP', 'mM'],
    'Deltaphi': ['Deltaphi', 'V'],
    'L_ArH': ['L_ArH', 'mol^2 J^-1 m^-2 s^-1'],
    'L_HH': ['L_HH', 'mol^2 J^-1 m^-2 s^-1'],
    'A_Ar': ['A_Ar', 'J mol^-1'],
    'J_H': ['J_H', 'mol m^-2 s^-1'],
    'J_K': ['J_K', 'mol m^-2 s^-1'],
    'J_Na': ['J_Na', 'mol m^-2 s^-1'],
    'J_Cl': ['J_Cl', 'mol m^-2 s^-1'],
}
