volume_orresu_dict = {
    'r_os': ['r_os', 'um'],
    'r_b': ['r_b', 'um'],
    'r': ['r', 'um'],
    'pi_t': ['pi_t', 'Pa', 'turgor pressure'],
    'R_ref': ['R_ref', 'um'],
    'c_i': ['c_i', 'mmol', 'internal concentration of osmolytes'],
    'V': ['V', 'fL'],
    'pi_i': ['pi_i', 'Pa'],
    'V_ref': ['V_ref', 'fL'],
    'G': ['G', '(um)^2'],
    'R_ref': ['R_ref', 'um s^-1'],
    'R_refdt': ['R_refdt', 'um'],
    'r_osdt': ['r_osdt', 'um'],
    'r_bdt': ['r_bdt', 'um'],
    'rdt': ['rdt', 'um'],
}
