hog_orresu_dict = {
    'Pbs2': ['Pbs2', 'mM', 'original/hog_model'],
    'Pbs2PP': ['Pbs2PP', 'mM', 'original/hog_model'],
    'Hog1c': ['Hog1c', 'mM', 'original/hog_model'],
    'Hog1PPc': ['Hog1PPc', 'mM', 'original/hog_model'],
    'Hog1n': ['Hog1n', 'mM', 'original/hog_model'],
    'Hog1PPn': ['Hog1PPn', 'mM', 'original/hog_model'],
    'Glyc_in': ['Glyc_in', 'mM', 'original/hog_model'],
    'Yt': ['Yt', 'mM', 'original/hog_model'],
    'V_os': ['V_os', 'fL', 'original/hog_model'],
    'z1': ['z1', 'mM', 'original/hog_model'],
    'z2': ['z2', 'mM', 'original/hog_model'],
    'z3': ['z3', 'mM', 'original/hog_model'],
    'z4': ['z4', 'mM', 'original/hog_model'],
    'NaCl': ['NaCl', 'mM'],
    'V_cell': ['V_cell', 'fL'],
    'V_cyt': ['V_cyt', 'fL'],
    'V_nuc': ['V_nuc', 'fL'],
    'PI_e': ['PI_e', 'Pa'],
    'PI_t': ['PI_t', 'Pa'],
    'PI_i': ['PI_i', 'Pa'],
    'V_ratio': ['V_ratio', 's^-1'],
    'n_totalHog1': ['n_totalHog1', 'mM fL'],
    'totalHog1PP': ['totalHog1PP', 'mM fL'],
}
