combined_models_orresu_dict = {
    # hog model
    'Pbs2': ['Pbs2', 'mM', 'original/hog_model'],
    'Pbs2PP': ['Pbs2PP', 'mM', 'original/hog_model'],
    'Hog1c': ['Hog1c', 'mM', 'original/hog_model'],
    'Hog1PPc': ['Hog1PPc', 'mM', 'original/hog_model'],
    'Hog1n': ['Hog1n', 'mM', 'original/hog_model'],
    'Hog1PPn': ['Hog1PPn', 'mM', 'original/hog_model'],
    'Glyc_in': ['Glyc_in', 'mM', 'original/hog_model'],
    'Yt': ['Yt', 'mM', 'original/hog_model'],
    'z1': ['z1', 'mM', 'original/hog_model'],
    'z2': ['z2', 'mM', 'original/hog_model'],
    'z3': ['z3', 'mM', 'original/hog_model'],
    'z4': ['z4', 'mM', 'original/hog_model'],
    'V_cell': ['V_cell', 'fL'],
    'V_cyt': ['V_cyt', 'fL'],
    'V_nuc': ['V_nuc', 'fL'],
    'pi_e': ['pi_e', 'Pa'],
    'pi_i': ['pi_i', 'Pa'],
    'pi_t': ['pi_t', 'Pa', 'turgor pressure', 'original/volume_model'],

    'V_ratio': ['V_ratio', 's^-1'],
    'n_totalHog1': ['n_totalHog1', 'mM fL'],
    'totalHog1PP': ['totalHog1PP', 'mM fL'],

    'V_os': ['V_os', 'fL'],
    'G': ['G', '(um)^2'],
    'R_refx': ['R_refx', 'um s^-1'],
    'R_refdt': ['R_refdt', 'um'],
    'r_osdt': ['r_osdt', 'um'],
    'r_bdt': ['r_bdt', 'um'],
    'rdt': ['rdt', 'um'],
    'c_e' :['c_e', 'mM'],
    'V_ref' : ['V_ref', 'fL'],

    # volume model
    'r_os': ['r_os', 'um'],
    'r_b': ['r_b', 'um'],
    'r': ['r', 'um'],
    'R_ref': ['R_ref', 'um', 'simulated/volume_model for V=58fl'],

    # ion model
    'H_in': ['H_in', 'mM'],
    'K_in': ['K_in', 'mM'],
    'Cl_in': ['Cl_in', 'mM'],
    'Na_in': ['Na_in', 'mM'],
    'H_out': ['H_out', 'mM'],
    'K_out': ['K_out', 'mM'],
    'Cl_out': ['Cl_out', 'mM'],
    'Na_out': ['Na_out', 'mM'],
    'Na_indt': ['Na_indt', 'mM'],
    'Cl_indt': ['Cl_indt', 'mM'],
    'K_indt': ['K_indt', 'mM'],
    'H_indt': ['H_indt', 'mM'],
    'Na_outdt': ['Na_outdt', 'mM'],
    'Cl_outdt': ['Cl_outdt', 'mM'],
    'K_outdt': ['K_outdt', 'mM'],
    'H_outdt': ['H_outdt', 'mM'],
    'Sorbitol_out': ['Sorbitol_out', 'mM'],

    'ATP': ['ATP', 'mM'],
    'Deltaphi': ['Deltaphi', 'V'],
    'L_ArH': ['L_ArH', 'mol^2 J^-1 m^-2 s^-1'],
    'L_HH': ['L_HH', 'mol^2 J^-1 m^-2 s^-1'],
    'A_Ar': ['A_Ar', 'J mol^-1'],
    'J_H': ['J_H', 'mol m^-2 s^-1'],
    'J_K': ['J_K', 'mol m^-2 s^-1'],
    'J_Na': ['J_Na', 'mol m^-2 s^-1'],
    'J_Cl': ['J_Cl', 'mol m^-2 s^-1'],

    'c_i': ['c_i', 'mM', 'internal concentration of osmolytes']
}

